### ISSUE TITLE
Issue when starting Client-UI

### ISSUE THREAD

**Issue by L0rDPSYCH0** [muhilkennedy/Learning-App-WebShopping#82]
Hi! 

I might be doing something wrong but I just cloned your repository, set up my local db... the backend part starts and it's working but whenever I open the Client-UI App.. it just stays frozen and I can't do anything. No errors in the console, no anything... it seems to try to load something but I have no idea what. 

![image](https://user-images.githubusercontent.com/12871744/99877395-8bb12380-2c06-11eb-8d04-d432d5fee87c.png)

Any ideas what might be causing this behaviour ?

**Comment by muhilkennedy** [comment]
we have not implemented client-ui yet... its just a starting page.... will be creating new client-ui project using react soon.
By the way fell free to check admin ui which is almost 70% complete... since im doing this project on leisure time it will take some more months to complete the entire client and admin ui

**Comment by L0rDPSYCH0** [comment]
I have tried it but... it seems to give me a decrypt error... Also what is the original user for logging to the admin ui ?
Is there a way for me of adding a new user (othar than inserting in the db directly) I can't do that since i don't know the encrypted value of the pw to be.?

**Comment by L0rDPSYCH0** [comment]
![image](https://user-images.githubusercontent.com/12871744/99878953-b81e6d00-2c11-11eb-9e84-fd04a5aa5b42.png)
This is happening while trying to login.

**Comment by muhilkennedy** [comment]
i used flyway lib.... u can see the schema and initial data load in v1__initial.sql
default user:
email -> q@1
password -> test
